import './swag-customized-products-option-type-base';
import './swag-customized-products-option-type-base-tree';
import './swag-customized-products-option-type-header';
import './swag-customized-products-option-type-surcharges';
import './swag-customized-products-option-type-advanced-surcharges';

import './swag-customized-products-option-type-checkbox';
import './swag-customized-products-option-type-colorpicker';
import './swag-customized-products-option-type-datetime';
import './swag-customized-products-option-type-fileupload';
import './swag-customized-products-option-type-imageselect';
import './swag-customized-products-option-type-timestamp';
import './swag-customized-products-option-type-textfield';
import './swag-customized-products-option-type-select';
import './swag-customized-products-option-type-colorselect';
import './swag-customized-products-option-type-numberfield';
import './swag-customized-products-option-type-htmleditor';
import './swag-customized-products-option-type-imageupload';
import './swag-customized-products-option-type-textarea';
